### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by mevanekanayake** [ajayn1997/Visual-Question-Answering-System#1]
https://drive.google.com/file/d/0B3b69xdtpDT8U2dwajNKOEhUWUU/view
https://visualqa.org/data/mscoco/vqa/Annotations_Val_mscoco.zip

These two link are not working. Could you please update the links.

**Comment by ajayn1997** [comment]
The Model weights have been deleted by the owner. You will have to train the entire model. As for the Annotations link, the organizers keep updating the dataset, so it is better to check out the parent link to see all the data available. If you are looking for the same data, I think its part of VQA1.0 in the following link:
https://visualqa.org/vqa_v1_download.html

**Comment by ajayn1997** [comment]
You can find the data and model weights here.
https://drive.google.com/drive/folders/1YtLsIRxME8zA2JhY4RmxUlgaNjh4eqaz?usp=sharing
