### ISSUE TITLE
Error in prepare_data.py

### ISSUE THREAD

**Issue by mevanekanayake** [ajayn1997/Visual-Question-Answering-System#2]
Two concerns w.r.t lines 28-30 in prepare_data.py

In line 28:
ques_data = np.array(ques_data['ques_train'])[:data_limit, :]
ques_data is converted to numpy array. Thus in line 29, calling "ques_data['ques_length_train'])" fails.

In line 30:
ques_train = right_align(ques_train, ques_length_train)
The variable ques_train is not defined earlier. Thus the code fails.

Could you please address these issues and provide solutions. Thank you in advance.

**Comment by mevanekanayake** [comment]
There is some mistake in lines 28-30 that I cannot figure out. Could you please help me with this.
Should "ques_data" in line 28 be replaced by "ques_train" ??

**Comment by ajayn1997** [comment]
Yes. It was a mistake in the code, I think line 28 "quest_data" can be replaced with "ques_train".

**Comment by ajayn1997** [comment]
I have pushed the fixed code.
