### ISSUE TITLE
Problem with Multiply

### ISSUE THREAD

**Issue by mevanekanayake** [ajayn1997/Visual-Question-Answering-System#3]
In the line 31 of models.py --> fc_model.add(Multiply([vgg_model, lstm_model]))
Gives below error:
TypeError: __init__() takes 1 positional argument but 2 were given

Could you kindly suggest a fix?

**Comment by ajayn1997** [comment]
Please check this link: https://keras.io/api/layers/merging_layers/multiply/#:~:text=tf.keras.layers.Multiply%28%2A%2Akwargs%29%20Layer%20that%20multiplies%20%28element-wise%29%20a%20list%20of,a%20single%20tensor%20%28also%20of%20the%20same%20shape%29.
Have pushed the fix.

**Comment by mevanekanayake** [comment]
Now I get this error.
ValueError: Layer multiply_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.engine.sequential.Sequential'>. Full input: [<keras.engine.sequential.Sequential object at 0x00000268CA87F358>, <keras.engine.sequential.Sequential object at 0x00000268CA87D7F0>]. All inputs to the layer should be tensors.

**I think for the method Multiply()([input1, input2]), the inputs should be tensors. Could you please suggest a solution?**

**Comment by ajayn1997** [comment]
Check this Link: https://stackoverflow.com/questions/45979848/merge-2-sequential-models-in-keras
I think you can change it accordingly. I think adding model.output will give the tensor required.

**Comment by mevanekanayake** [comment]
I followed your instructions and used the tensors generated by model.output as the arguments for the Multiply( )
Also, I changed the proceeding lines accordingly following the instructions in the link you shared. Link: https://stackoverflow.com/questions/45979848/merge-2-sequential-models-in-keras

Find the solution in my repo.
https://github.com/mevanekanayake/Visual-Question-Answering-System
